/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_image_t (XDR *xdrs, image_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->image.image_val, (u_int *) &objp->image.image_len, ~0))
		 return FALSE;
	return TRUE;
}
