/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct image_t {
	struct {
		u_int image_len;
		char *image_val;
	} image;
};
typedef struct image_t image_t;

#define MINIFYJPEG_PROG 0x31230000
#define MINIFYJPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1(image_t , image_t *, CLIENT *);
extern  bool_t minifyjpeg_proc_1_svc(image_t , image_t *, struct svc_req *);
extern int minifyjpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1();
extern  bool_t minifyjpeg_proc_1_svc();
extern int minifyjpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_image_t (XDR *, image_t*);

#else /* K&R C */
extern bool_t xdr_image_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
